-- Auto-generated from schema-map-postgres.psd1 (map@62c9c93)
-- engine: postgres
-- table:  key_usage
CREATE TABLE IF NOT EXISTS key_usage (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key_id BIGINT NOT NULL,
  usage_date DATE NOT NULL,
  encrypt_count INTEGER NOT NULL DEFAULT 0,
  decrypt_count INTEGER NOT NULL DEFAULT 0,
  verify_count  INTEGER NOT NULL DEFAULT 0,
  last_used_at TIMESTAMPTZ(6) NULL,
  CONSTRAINT chk_key_usage_counts CHECK (
    encrypt_count >= 0 AND decrypt_count >= 0 AND verify_count >= 0
  ),
  CONSTRAINT uq_key_usage_key_date UNIQUE (key_id, usage_date)
);
