-- Auto-generated from schema-map-postgres.psd1 (map@mtime:2025-10-24T09:46:38Z)
-- engine: postgres
-- table:  key_usage
CREATE TABLE IF NOT EXISTS key_usage (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key_id BIGINT NOT NULL,
  "date" DATE NOT NULL,
  encrypt_count INTEGER NOT NULL DEFAULT 0,
  decrypt_count INTEGER NOT NULL DEFAULT 0,
  verify_count  INTEGER NOT NULL DEFAULT 0,
  last_used_at TIMESTAMPTZ(6) NULL,
  CONSTRAINT uq_key_usage_key_date UNIQUE (key_id, "date")
);
